spring.application.name=mini-redis

server.port=8080
spring.main.banner-mode=off

# Logging
logging.level.root=INFO
logging.level.com.miniredis=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
