spring.application.name=mini-redis

# Spring Shell settings
spring.shell.interactive.enabled=true
spring.main.banner-mode=off
spring.shell.command.quit.enabled=false

# Logging
logging.level.root=INFO
logging.level.com.miniredis=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
